apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: awb-root
spec:
  type: file            # ← explicite (ou laissez vide)
  rules:
    - allow: [Group, Component, Template]
  targets:
    - ./groups/infra-group.yaml
    - ./templates/create-vm/template.yaml


# ↘  NOUVELLE Location, on pointe le dossier (pas de *.yaml)
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: awb-components
spec:
  rules:
    - allow: [Component]
  targets:
    - ./components/*.yaml

