apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: awb-entities
spec:
  rules: 
    - allow: [System, Group, User]    # ajoutez toutes les kinds nécessaires
  targets:
    - ./organization.yaml
    - ./locations.yaml
