apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ec2-micro
  title: VM micro (EC2.micro)
  description: Instance EC2 gérée par Crossplane
  annotations:
    # ← indique au plugin dans quel cluster chercher
    backstage.io/managed-by-location: "kubernetes: microk8s-cluster"

    # ← permet d’identifier le namespace
    backstage.io/kubernetes-label-selector: |
      crossplane.io/claim-name=ec2-micro
      crossplane.io/claim-namespace=crossplane-system


    # ← coordonnées complètes du claim
    terasky.backstage.io/claim-name:    ec2-micro
    terasky.backstage.io/claim-plural:  virtualmachines
    terasky.backstage.io/claim-group:   platform.example.org
    terasky.backstage.io/claim-version: v1alpha1

    # ← déjà correct
    crossplane.io/kubernetes-cluster: microk8s-cluster::microk8s

spec:
  type: crossplane-claim
  lifecycle: production
  owner: group:infra
