apiVersion: backstage.io/v1alpha1 
kind: Component
metadata:
  name: ec2-micro-1                    # ← toujours conforme
  title: VM micro (ec2.micro.1)
  description: Instance EC2 gérée par Crossplane
  annotations:
    crossplane.io/claim-group:   platform.example.org
    crossplane.io/claim-version: v1alpha1
    crossplane.io/claim-kind:    VirtualMachine
    crossplane.io/claim-name:    ec2-micro-1
    crossplane.io/kubernetes-cluster: microk8s-cluster
    crossplane.io/namespace:     default
spec:
  type: crossplane-claim
  lifecycle: production
  owner: group:infra