apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ec2-micro
  title: VM micro (EC2.micro)
  description: Instance EC2 gérée par Crossplane
  annotations:
    # ⬇️ CLUSTER :: CONTEXT  (deux fois le même nom si vous n’avez qu’un contexte)
    crossplane.io/kubernetes-cluster: microk8s-cluster::microk8s
    backstage.io/kubernetes-label-selector: crossplane.io/claim-name=ec2-micro,crossplane.io/claim-namespace=default

    # ─── autres clés requises par le plugin ─────────────────────────────
    crossplane.io/claim-api-version: platform.example.org/v1alpha1
    crossplane.io/claim-kind:  VirtualMachine
    crossplane.io/claim-name:  ec2-micro
    crossplane.io/namespace:   default

spec:
  type: crossplane-claim
  lifecycle: production
  owner: group:infra
