apiVersion: backstage.io/v1alpha1 
kind: Component
metadata:
  name: ec2-micro                    # ← toujours conforme
  title: VM micro (EC2.micro)
  description: Instance EC2 gérée par Crossplane
  annotations:
    crossplane.io/claim-group:   platform.example.org
    crossplane.io/claim-version: v1alpha1
    crossplane.io/claim-kind:    VirtualMachine
    crossplane.io/claim-name:    ec2-micro
    crossplane.io/kubernetes-cluster: microk8s
    crossplane.io/namespace:     default
spec:
  type: VM
  lifecycle: production
  owner: group:infra