# ─────—— Organisation ─────——
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: sig
  title: SIG
spec:
  type: organization
  children: [production]

---
# ─────—— Département ─────——
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: production
  title: Département Production
spec:
  type: department
  parent: sig
  children: [infra]

---
# ─────—— Équipe (team) ─────——
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: infra
  title: Équipe Infra
spec:
  type: team
  parent: production
  children: []          

