# ─────—— Organisation ─────——
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: sig
  title: SIG
  namespace: default

spec:
  type: organization
  children: [production]

---
# ─────—— Département ─────——
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: production
  title: Département Production
  namespace: default

spec:
  type: department
  parent: sig
  children: [infra]

# ─────—— Département ─────——
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: DC
  title: Département DC
  namespace: default

spec:
  type: department
  parent: sig
  children: [vente]
---
# ─────—— Équipe (team) ─────——
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: vente
  title: Équipe Vente
  namespace: default
spec:
  type: team
  parent: DC
  children: []          

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: infra
  title: Équipe Infra
  namespace: default
spec:
  type: team
  parent: production
  children: []   