
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: awb-sig
  title: Système d'Information Groupe(SIG)
  description: Système d'Information Groupe
  links:
    - url: http://www.attijariwafabank.com/
      title: Website
spec:
  type: organization
  profile:
    displayName: AWB SIG
    email: sig@attijariwafa.com
  children: [production]




