apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-vm
  title: Créer une VM via Crossplane
spec:
  owner: group:infra
  type: service

  parameters:
    - title: Informations de la VM
      required: [name, size]
      properties:
        name:
          type: string
        size:
          type: string
          enum: [micro, nano, small]
          default: micro

  steps:
    # 1️⃣  Copie du squelette
    - id: fetch
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}              # ex. ec2.micro
          size: ${{ parameters.size }}
          slug: ${{ parameters.name | lower | replace(".", "-") }}
      #  "ec2.micro" ➜ "ec2-micro"


    # 2️⃣  Création ou mise-à-jour de la PR
    - id: publish
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=Younesic&repo=backstage-catalog
        branchName: backstage-integration
        title: "Ajout du composant ${{ parameters.name }}"
        description: "Composant généré par le template create-vm"
        # ↓ Le fichier catalog-info.yaml copié par l’étape fetch sera
        #   rangé ici dans la PR
        targetPath: components/${{ parameters.name | lower }}.yaml
        catalogInfoPath: components/${{ values.slug }}.yaml
        update: true                       # si la PR existe déjà, on ajoute

    # 3️⃣  Enregistrement dans le catalogue
    - id: register
      action: catalog:register
      input:
        # branche créée / mise-à-jour par l’étape publish
        repoContentsUrl: https://github.com/Younesic/backstage-catalog/blob/backstage-integration
        catalogInfoPath: components/${{ values.slug }}.yaml


  output:
    links:
      - title: Pull request
        url: ${{ steps.publish.output.pullRequestUrl }}
      - title: Voir dans le catalogue
        url: "{{ catalogInfoUrl }}"
