apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-vm
  title: Créer une VM via Crossplane
  description: Provisionner une VM à l'aide d'une Claim Crossplane
spec:
  owner: group:infra
  type: service

  parameters:
    - title: Informations de la VM
      required: [name, size]
      properties:
        name:
          type: string
          title: Nom de la VM
        size:
          type: string
          title: Taille de la VM
          enum: [micro, nano, small]
          default: micro

  steps:
    # 1️⃣  Copie du squelette
    - id: fetch
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}                 # ex. ec2.micro
          size: ${{ parameters.size }}
          slug: ${{ parameters.name | lower | replace(".", "-") }}
          #                "ec2.micro" ➜ "ec2-micro"

    # 2️⃣  PR (ou mise à jour) dans le dépôt
    - id: publish
      name: Créer la pull request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=Younesic&repo=backstage-catalog
        branchName: backstage-integration
        title: "Ajout du composant ${{ parameters.name }}"
        description: "Composant généré par le template create-vm"   # ← AJOUTE ceci
        targetPath: components/${{ values.slug }}.yaml        # ① chemin réel du fichier
        update: true


    # 3️⃣  Enregistrement dans le catalogue
    - id: register
      action: catalog:register
      input:
        repoContentsUrl: https://github.com/Younesic/backstage-catalog/tree/backstage-integration   # ② « tree », pas « blob »
        catalogInfoPath: components/${{ values.slug }}.yaml                                          # ③ même slug que ci-dessus



  output:
    links:
      - title: Pull request GitHub
        url: ${{ steps.publish.output.pullRequestUrl }}
      - title: Voir dans le catalogue
        url: "{{ catalogInfoUrl }}"
