apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-vm
  title: Créer une VM via Crossplane
  description: Provisionner une VM à l'aide d'une Claim Crossplane
spec:
  owner: group:infra
  type: service

  parameters:
    - title: Informations de la VM
      required: [name, size]
      properties:
        name:
          type: string
          title: Nom de la VM
        size:
          type: string
          title: Taille de la VM
          enum: [micro, nano, small]
          default: micro

  steps:
    # 1️⃣  Copie des fichiers dans le workspace temporaire
    - id: fetch
      name: Préparer les fichiers
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          size: ${{ parameters.size }}

    # 2️⃣  Création de la PR dans le dépôt catalog
    - id: publish
      name: Créer la pull request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=Younesic&repo=backstage-catalog
        branchName: backstage-integration
        title: "Ajout du composant ${{ parameters.name }}"
        description: "Composant généré par le template create-vm"
        targetPath: ""                    # racine du dépôt
        update: true
        # le workspace courant sera entièrement ajouté à la PR

    # 3️⃣  Enregistrement dans le catalogue
    - id: register
      name: Publier dans le catalogue
      action: catalog:register
      input:
        # URL racine du dépôt + branche créée à l’étape précédente
        repoContentsUrl: https://github.com/Younesic/backstage-catalog/blob/backstage-integration
        # Chemin du fichier que le template vient d’ajouter
        catalogInfoPath: components/${{ parameters.name | lower }}.yaml


  output:
    links:
      - title: Pull request GitHub
        url: ${{ steps.publish.output.pullRequestUrl }}
      - title: Voir dans le catalogue
        url: "{{ catalogInfoUrl }}"
