apiVersion: backstage.io/v1alpha1 
kind: Component
metadata:
  name: ${{ values.slug }}                    # ← toujours conforme
  title: VM ${{ values.size }} (${{ values.name }})
  description: Instance EC2 gérée par Crossplane
  annotations:
    crossplane.io/claim-group:   platform.example.org
    crossplane.io/claim-version: v1alpha1
    crossplane.io/claim-kind:    VirtualMachine
    crossplane.io/claim-name:    ${{ values.slug }}
    crossplane.io/kubernetes-cluster: microk8s-cluster
    crossplane.io/namespace:     default
spec:
  type: crossplane-claim
  lifecycle: production
  owner: group:infra